[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "advent"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
itertools = "0.12"
regex = "1.10"
